x = int(input('Entre com o número '))
print('1x{} é {}'.format(x, x))
print('2x{} é {}'.format(x, x*2))
print('3x{} é {}'.format(x, x*3))
print('4x{} é {}'.format(x, x*4))
print('5x{} é {}'.format(x, x*5))
print('6x{} é {}'.format(x, x*6))
print('7x{} é {}'.format(x, x*7))
print('8x{} é {}'.format(x, x*8))
print('9x{} é {}'.format(x, x*9))
print('10x{} é {}'.format(x, x*10))
