word = (input('Digite algo: '))
print('O tipo é ', type(word))
print('É somente espaços?', word.isspace())
print('É númerico?', word.isalnum())
print('É alfabetico?', word.isalpha())
print('É alfanumerico?', word.isalnum())
print('Está em maisculo?', word.isupper())
print('Está em minusculo?', word.islower())
print('Está capitalizado?', word.istitle())
